# Generated by Django 2.1 on 2018-08-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('preview_image', models.ImageField(upload_to='posts/preview_images/%Y/%m/%d', verbose_name='Превью изображение')),
            ],
            options={
                'verbose_name': ('Пост',),
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
