# Generated by Django 2.1 on 2018-08-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180804_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Картинка из поста', 'verbose_name_plural': 'Картинки постов'},
        ),
        migrations.AddField(
            model_name='post',
            name='is_created',
            field=models.BooleanField(default=False, verbose_name='Создан'),
        ),
    ]
