# Generated by Django 2.1 on 2018-09-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180824_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=512, verbose_name='Текст'),
        ),
    ]
